env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
rules:
  indent: ['error', 'tab']
globals:
  cool_bio_profiles: readonly
